spring:
  datasource:
    url: jdbc:h2:file:./data/mytestdb;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: false
