-- liquibase formatted sql

-- changeset Nikita:1744552047864-1
CREATE TABLE cards
(
    id               UUID         NOT NULL,
    encrypted_number VARCHAR(255) NOT NULL,
    masked_number    VARCHAR(255) NOT NULL,
    card_holder      VARCHAR(255) NOT NULL,
    expiry_date      date         NOT NULL,
    card_type        VARCHAR(255) NOT NULL,
    status           VARCHAR(255) NOT NULL,
    balance          DECIMAL      NOT NULL,
    user_id          BIGINT       NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_cards PRIMARY KEY (id)
);

-- changeset Nikita:1744552047864-2
CREATE TABLE transactions
(
    id          UUID         NOT NULL,
    card_id     UUID         NOT NULL,
    amount      DECIMAL      NOT NULL,
    description VARCHAR(255),
    timestamp   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    type        VARCHAR(255) NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

-- changeset Nikita:1744552047864-3
CREATE TABLE user_roles
(
    user_id BIGINT       NOT NULL,
    roles   VARCHAR(255) NOT NULL
);

-- changeset Nikita:1744552047864-4
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset Nikita:1744552047864-5
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset Nikita:1744552047864-6
ALTER TABLE cards
    ADD CONSTRAINT FK_CARDS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset Nikita:1744552047864-7
ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_CARD FOREIGN KEY (card_id) REFERENCES cards (id);

-- changeset Nikita:1744552047864-8
ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);

